name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache Maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: |
        lein deps
        lein create-bundle-config gorilla
        cd out/bundles/gorilla && npm install
        cd out/bundles/gorilla && ./node_modules/.bin/shadow-cljs -v release gorilla
    - name: Check formatting
      run: lein cljfmt check
    - name: Run tests
      run: |
        lein test
    - name: Release
      env:
        RELEASE_USERNAME: ${{ secrets.ReleaseUsername }}
        RELEASE_PASSWORD: ${{ secrets.ReleasePassword }}
      # TODO: Git status/checkout -f - hacky as f***!
      run: |
        git config --global user.email "ci@pinkgorilla.org"
        git config --global user.name "CI/CD"
        lein with-profile +cljs jar
        git status
        git checkout -f package.json
        git checkout -f package-lock.json
        #
        # Could not transfer metadata foo:bar/maven-metadata.xml from/to releases (https://clojars.org/repo): Read timed out
        # Default 10000 not enough for us
        #
        export LEIN_JVM_OPTS="-Dmaven.wagon.rto=90000"
        lein release
